// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPjDRtSCnOwCKTlMOPCoMSZIRzbWG53uA',
    appId: '1:340594378195:web:81c88d013cf4bb43b3db26',
    messagingSenderId: '340594378195',
    projectId: 'fir-task-c1b25',
    authDomain: 'fir-task-c1b25.firebaseapp.com',
    storageBucket: 'fir-task-c1b25.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDctOkuwx_PRawPRWeY-DziC_nTcGeVVYo',
    appId: '1:340594378195:android:4f6a1b2d79ef10beb3db26',
    messagingSenderId: '340594378195',
    projectId: 'fir-task-c1b25',
    storageBucket: 'fir-task-c1b25.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_mx93GqLCSsB5vKf4WweuJe-B06kKH68',
    appId: '1:340594378195:ios:fce1ca143c9af493b3db26',
    messagingSenderId: '340594378195',
    projectId: 'fir-task-c1b25',
    storageBucket: 'fir-task-c1b25.appspot.com',
    iosClientId: '340594378195-kimrgnsg6aeus5dbdrah0ro6ncsm2pb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_mx93GqLCSsB5vKf4WweuJe-B06kKH68',
    appId: '1:340594378195:ios:fce1ca143c9af493b3db26',
    messagingSenderId: '340594378195',
    projectId: 'fir-task-c1b25',
    storageBucket: 'fir-task-c1b25.appspot.com',
    iosClientId: '340594378195-kimrgnsg6aeus5dbdrah0ro6ncsm2pb8.apps.googleusercontent.com',
    iosBundleId: 'com.example.firebaseTask',
  );
}
